integration:
  moip:
    ccHash: "HhL0kbhfid+jwgj5l6Kt9EPdetDxQN8s7uKUHDYxDC/XoULjzik44rSda3EcWuOcL17Eb8JjWc1JI7gsuwg9P0rJv1mJQx+d3Dv1puQYz1iRjEWWhnB1bw0gTvnnC/05KbWN5M8oTiugmhVK02Rt2gpbcTtpS7VWyacfgesBJFavYYMljYg8p2YGHXkXrMuQiOCeemKLk420d0OTMBba27jDVVJ663HZDrObnjFXJH/4B5irkj+HO5genV+V4PYoLcOESG4nrI3oFAsMGsLLcdJo0NNvkEmJpn0e9GzureKKFYisYU+BEd9EMr/odS0VMvOYRV65HbPTspIkjl2+3Q=="
    token: "01010101010101010101010101010101"
    key: "ABABABABABABABABABABABABABABABABABABABAB"
    dateFormat: "yyyy-MM-dd"

# config context path to "/" by setting an empty string
server:
  contextPath:

# JACKSON
spring:
  jackson:
    serialization-inclusion: "non_null"
    serialization:
      INDENT_OUTPUT: true
  data.rest.base-path: "/api"

jwt:
  header: Authorization
  scheme: Bearer
  secret: Senha
  expiration: 28800 #seconds -> 8 hours
#  expiration: 30 #seconds -> test
  route:
    user:
      path: "/api/v1/users"
    authentication:
      path: "/api/v1/auth"